# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bf2c20d5779acf427c976cc30f70f04c3e459cbce111e3e0639ad481484d0bf3218f9410add21c87ee82aac062b4da9d1a4b3fcabac2897f1d490eb236909b2

test:
  secret_key_base: 9e46f0911ad87a4f0149eed6ba3857498d29c536195e00fa21647a418ab5eacb96601ea4b2aec08489b130f20983c60850f9442ed2c4a1ed6e9ba14e558e1d83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
